### ISSUE TITLE
Copy from outside the program not pastable

### ISSUE THREAD

**Issue by filipesilva** [t9md/atom-clip-history#3] opened 2015-07-15 15:42 UTC
I suppose this is by design - obviously it is not feasible to log all copy-paste in the OS. Still I wanted to make an issue in case someone else thinks of asking.

Is it maybe possible to capture the current clipboard on editor focus, and add it to the stack? I'm not familiar with atom's API so I do not know if this is even available.

**Comment by t9md** [comment] 2015-07-16 00:14
Yes, I want do this.
Actually, it was included in this package before, but currently I disable it.
https://github.com/t9md/atom-clip-history/blob/master/lib/main.coffee#L170-L173

I can capture system's clipboard before pasting. 
But problem is, when clip-history's latest entry and system's clipboard is different, I can't determine which is the newer one.
After I find some solution this feature would be back.

**Comment by filipesilva** [comment] 2015-07-16 08:56
Hm. Interesting problem. Atom clipboard api does not return timestamps, so that cannot be used.

If you mark the last synced entry on the history, you can know if the current sync has new data or not. That would suffice, no?

**Comment by t9md** [comment] 2015-07-16 09:09
I'm getting complicated, I forgot why I couldn't use "peeking system clipboard before paste and if different it treat as latest history entry" solution.

I'll try again.
After I figure out what the problem is I maybe re-include this feature to clip-history, or I could solve this problem using Chrome's localStorage to immediately sync history entries between multiple atom windows.

**Comment by filipesilva** [comment] 2015-07-16 10:08
Yeah as I was thinking about it more, it didn't quite get the scenario where peeking wouldn't work. If you remember can you tell me?

**Comment by t9md** [comment] 2015-10-30 18:31
Released in v0.1.12

**Closed as completed by t9md** 2015-10-30 18:31 UTC
